[build]
cmd = "swag init --output ./docs --dir ./cmd/api && go build -o ./tmp/main ./cmd/api/main.go"
bin = "./tmp/main"
include_ext = ["go", "yaml", "yml"]  # Отслеживаем Go-файлы и конфиги Swagger
exclude_dir = ["tmp", "vendor", "docs"]  # Исключаем docs, чтобы избежать цикла
delay = 1000

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

